### ISSUE TITLE
Typos in quick trial description for "HelloThemisto"

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloThemisto#2]
1) two "-" needed in front of "recursive" option
`git clone -recursive git@github.com:cloudFPGA/cFp_HelloThemisto.git` --> `git clone --recursive git@github.com:cloudFPGA/cFp_HelloThemisto.git`   
2) `./sra/build pr` --> `./sra build pr`

**Comment by fab7** [comment]
The PR flow of the file 
Doc/docsrc/pages/GETTING_STARTED/getting_started.md
was updated as well as the related cFp_HelloThemisto project.

**Comment by zrlhle** [comment]
Thank you
