### ISSUE TITLE
Copy of "user.json" file from cFSP to cFp_HelloThemisto fails because the scripts "sra" and "cfsp" expect a different format 

### ISSUE THREAD

**Issue by zrlhle** [cloudFPGA/cFp_HelloThemisto#3]
diff ${SANDBOX}/cFp_HelloThemisto/user.json ${SANDBOX}/cFSP/user.json
```
1c1
< {"credentials": {"user": "hle", "pw": "XYZ"}, "project": "cf_Test_2"}
---
> {"credentials": {"username": "hle", "password": "XYZ"}, "project": "cf_Test_2"}
```

**Comment by bringlein** [comment]
Good hint, thanks. Should be fixed ([cFCreate-commit](https://github.com/cloudFPGA/cFCreate/commit/4b5a0bd33c8783049cbe6e6f642475a5557e9316)). Please update cFCreate with git pull, then run `./cFCreate update path/to/cFp_HelloThemisto`.

**Comment by zrlhle** [comment]
Please also fix the description in Step3 of the top-level "cFp_HelloThemisto" README.md, which still says 
```
  $ echo "{\"credentials\": {\"user\": \"YOUR_USERNAME\", \"pw\": \"YOUR_PASSWORD\" }, \"project\": \"YOUR_PROJECTNAME\"}" > user.json
 ```

**Comment by zrlhle** [comment]
Thank you, closing
